# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        git push --prune https://$(GITHUB_PAT)@github.com/$REPO_NAME \
            +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
      displayName: 'Copy to Github'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
          $(tag)

