# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - bash: |
        git remote add guiterrube https://git@github.com/EdyKnopfler/unyleya_projeto_cicd_ederson_ferreira.git
        git pull guiterrube main
        git push
      displayName: 'Sincronizando do GitHub'
      #condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
          $(tag)

